# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  solutionName: 'DabarBlog.sln'

steps:
- script: | 
  dotnet build $(solutionName) --configuration $(buildConfiguration)
  dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
  dotnet publish src/App/App.csproj --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
