# build: docker-compose -f "docker-compose.yml" -f "docker-compose.override.yml" -f "docker-compose.sqlserver.yml" up -d --build

version: '3.4'

services:
  bet.blog.webapp:
    environment:
      - ConnectionStrings:SqlServerConnection=Server=app.sqldb;Database=aspnetapp;User Id=sa;Password=Pass@word

  bet.blog.sqldb:
    image: microsoft/mssql-server-linux
    ports:
     - "5468:1433"
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
