# build: docker-compose -f "docker-compose.yml" -f "docker-compose.override.yml" up -d --build

version: '3.4'

services:
  bet.blog.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6001
      - EnableHttpsRedirection=true
      
      # in order for this key vault to work run appauthentication run --verbose:debug before opening the application in the visual studio code.
      - MSI_ENDPOINT=${MSI_ENDPOINT}
      - MSI_SECRET=${MSI_SECRET}

    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
