version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}dabarblog
    build:
      context: .
      dockerfile: src/App/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        PROJECT_PATH: "/src/App/App.csproj"
        SOLUTION_BASE: "false"
