version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}dabarblog
    build:
      context: .
      dockerfile: src/App/Dockerfile
      args:
       sdkImage: kdcllc/dotnet
       sdkTag: 2.2-sdk
       runtimeImage: mcr.microsoft.com/dotnet/core/aspnet
       runtimeTag: 2.2
       coreversion: netcore22
#        sdkImage: kdcllc/dotnet
#        sdkTag: 3.0-sdk
#        runtimeImage: mcr.microsoft.com/dotnet/core/aspnet
#        runtimeTag: 3.0
#        coreversion: netcore30

  app.sqldb:
   image: microsoft/mssql-server-linux