# build: docker-compose -f "docker-compose.yml" -f "docker-compose.override.yml" up -d --build

version: '3.4'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6001
      - ConnectionStrings:SqlServerConnection=Server=app.sqldb;Database=aspnetapp;User Id=sa;Password=Pass@word
      - Serilog:WriteTo:Args:pathFormat=app/Logs/DabarBlog-log-{Date}.json

    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  app.sqldb:
    image: microsoft/mssql-server-linux
    ports:
     - "5468:1433"
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
