version: '3.4'

services:

  bet.blog.base:
    image: betblogbase:v1
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SOLUTION_BASE: "true"
        NUGET_RESTORE: "-v d"
        RUNTESTS: "false"
        VERBOSE: "false"

  bet.blog.webapp:
    image: kdcllc/betblog:v1
    build:
      context: .
      dockerfile: src/Bet.Blog.WebApp/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        PROJECT_PATH: "/src/Bet.Blog.WebApp/Bet.Blog.WebApp.csproj"
        SOLUTION_BASE: "false"
    depends_on:
      - bet.blog.base
