version: '3.4'

services:
  base:
    image: betblogbase:v1
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SOLUTION_BASE: "true"
        NUGET_RESTORE: "-v d"
        RUNTESTS: "false"
        VERBOSE: "false"
  app:
    image: kdcllc/betblog:v1
    build:
      context: .
      dockerfile: src/App/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        PROJECT_PATH: "/src/App/App.csproj"
        SOLUTION_BASE: "false"
    depends_on:
      - base
